// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm4plD9HIxMt1A8IIM6xUM0OxWJJU3nGs',
    appId: '1:140295569789:web:13044f6ae90f1779418c14',
    messagingSenderId: '140295569789',
    projectId: 'power-b4433',
    authDomain: 'power-b4433.firebaseapp.com',
    storageBucket: 'power-b4433.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3P44t1yZXQ0zPXSbE2dJsV0Xnu3D34qg',
    appId: '1:140295569789:android:59d0cff24ff99d43418c14',
    messagingSenderId: '140295569789',
    projectId: 'power-b4433',
    storageBucket: 'power-b4433.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGqXcxZSdpiOlK8GTUQWyS1RmAzwcnjOU',
    appId: '1:140295569789:ios:41b5771e34c34bf6418c14',
    messagingSenderId: '140295569789',
    projectId: 'power-b4433',
    storageBucket: 'power-b4433.firebasestorage.app',
    iosBundleId: 'com.example.power',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGqXcxZSdpiOlK8GTUQWyS1RmAzwcnjOU',
    appId: '1:140295569789:ios:41b5771e34c34bf6418c14',
    messagingSenderId: '140295569789',
    projectId: 'power-b4433',
    storageBucket: 'power-b4433.firebasestorage.app',
    iosBundleId: 'com.example.power',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDm4plD9HIxMt1A8IIM6xUM0OxWJJU3nGs',
    appId: '1:140295569789:web:aaa50f9950cdadb9418c14',
    messagingSenderId: '140295569789',
    projectId: 'power-b4433',
    authDomain: 'power-b4433.firebaseapp.com',
    storageBucket: 'power-b4433.firebasestorage.app',
  );

}